Feat: Add RoomDetailViweController and Views
DeveloperAcademy-POSTECH/MC3-Team-18-Momin pull request #14
Opened 2022-07-20 13:59 UTC by Minkyeong-Ko

## Changes

<img width="556" alt="스크린샷 2022-07-20 오후 10 39 47" src="https://user-images.githubusercontent.com/78426896/179997125-756ead31-cdce-41b0-81bc-e83c4d3a9a0f.png">

- RoomDetail 폴더 추가
- RoomDetailViewController (추가)
- RoomDetailView (추가)
- SeparatedRoomView (추가)

## New features

- RoomDetailView를 보여주는 뷰 컨트롤러 추가
- RoomDetailView의 스택 뷰 안에 들어갈 SeparatedView 추가

## Review points

- SeparatedView에 Student 인스턴스를 전달하면 그에 맞는 뷰를 그리게 하였습니다
- Data 폴더에 있는 목데이터를 사용하면 RoomDetailView에 DormRoom을 전달하고, DormRoom.currentMembers 안의 학번을 가지고 목 데이터의 students 배열에서 해당 학생을 찾아야 하는데 아직 그 부분을 구현하지 못해 임시 데이터로 작업하였습니다

## Questions

- SeparatedRoomView에서 state에 따라 다른 아이콘을 보여줄 때 if문을 안쓰려고 enum을 사용해 봤는데 뭔가 많이 아닌 것 같은 느낌이 듭니다.. 좋은 방법 있을까요? 

## Checklist

- [ ] Is the branch you are merging on correct?
- [ ] Do you comply with coding conventions?
- [ ] Are there any changes not related to PR?
- [ ] Has my code been self-reviewed?

2022-07-20 14:18 UTC, HoJongPARK requested changes
코멘트 단 내용을 한 번 고려해보시면 좋을 것 같아요! 고생하셨습니다.

2022-07-20 14:18 UTC, HoJongPARK commented on dorm/dorm/Presenter/RoomManager/RoomDetail/RoomDetailView.swift
> +        roomDetailStackView.bottomAnchor.constraint(equalTo: self.bottomAnchor, constant: -10).isActive = true
NSLayoutConstraint.activate 함수를 사용하면 좀 더 간단하게 제약조건을 걸 수 있습니다!

2022-07-20 14:18 UTC, HoJongPARK commented on dorm/dorm/Presenter/RoomManager/RoomDetail/SeparatedRoomView.swift
> +//    }
사용하지 않는 코드인가요? 사용하지 않는 코드면 지우면 될 것 같습니다!

2022-07-20 14:18 UTC, HoJongPARK commented on dorm/dorm/Presenter/RoomManager/RoomDetail/SeparatedRoomView.swift
> +        studentInfo.topAnchor.constraint(equalTo: roomNumberLabel.bottomAnchor, constant: 20).isActive = true
이 부분도 마찬가지로 NSLayoutConstraint.activate 를 사용하면 간단해질 것 같습니다. 또한 roomNumberLabel 을 설정하는 부분과 scrollView 를 설정하는 부분을 따로 함수로 만들면 코드가 훨씬 간단해질 것 같아요

2022-07-20 14:18 UTC, HoJongPARK commented on dorm/dorm/Presenter/RoomManager/RoomDetail/SeparatedRoomView.swift
> +    }
제 생각에는 학생의 상태에 따른 이미지와 상태 문자열을 여러 곳에서 사용할 것 같습니다. 

따라서 SeparatedRoomView 라는 class 내부에 enum 을 사용해 적절한 이미지 이름을 얻기 보다는, student 인스턴스로부터 바로 이미지와 상태 문자열을 얻어올 수 있도록 구현할 것 같습니다.

https://github.com/DeveloperAcademy-POSTECH/MC3-Team-18-Momin/blob/00e52b919b2fdf5662b0597cac0c6bdb4938710c/dorm/dorm/Domain/Model/Student.swift#L40-L51

위는 이미 구현한 학생 상태에 따라 사람이 읽을 수 있는 상태 문자열을 가져오는 코드입니다.

학생 상태에 따라 알맞은 이미지를 얻어오고 싶으면, 다음과 같은 방법을 취할 것 같습니다

```swift
#if canImport(UIKit) // 이게 맞는지 모르겠습니다
var stateIcon: UIImage? {
switch 학생 상태 {
상태 Int 에 따라 알맞은 UIImage 를 반환해준다. 만약 정의되지 않은 상태라면 fatalError 로 강제로 에러 발생
}
#endif
```

2022-07-20 15:10 UTC, Minkyeong-Ko commented on dorm/dorm/Presenter/RoomManager/RoomDetail/RoomDetailView.swift
> +        roomDetailStackView.bottomAnchor.constraint(equalTo: self.bottomAnchor, constant: -10).isActive = true
알려주셔서 감사해요! 수정 완료 했습니다 :)

2022-07-20 15:10 UTC, Minkyeong-Ko commented on dorm/dorm/Presenter/RoomManager/RoomDetail/SeparatedRoomView.swift
> +//    }
삭제했습니다!

2022-07-20 15:10 UTC, Minkyeong-Ko commented on dorm/dorm/Presenter/RoomManager/RoomDetail/SeparatedRoomView.swift
> +        studentInfo.topAnchor.constraint(equalTo: roomNumberLabel.bottomAnchor, constant: 20).isActive = true
해당 부분도 반영해서 새로 커밋하였습니다!

2022-07-21 01:14 UTC, italsehf reviewed
되게 복잡해보이는데 역시 WWDC Winner는 다르네요👏🏻 감사합니다 ~~

2022-07-23 11:52 UTC, HoJongPARK requested changes

2022-07-23 11:52 UTC, HoJongPARK commented on dorm/dorm/Presenter/RoomManager/RoomDetail/RoomDetailView.swift
> +    ]
student 배열에다가 값을 바로 넣어주는게 아니라, initializer 에서 student 배열을 주입받는 형식으로 구현해서 나중을 대비하는게 어떨까요?
```swift
init(_ students: [Student] {
    self.students = students
}
```

2022-07-23 11:52 UTC, HoJongPARK commented on dorm/dorm/Presenter/RoomManager/RoomDetail/RoomDetailView.swift
> +    }()
클로저를 활용해서 StackView 의 설정을 StackView 자기 자신에게 맡기는 코드 아주 좋은 것 같습니다.

2022-07-23 11:52 UTC, HoJongPARK commented on dorm/dorm/Presenter/RoomManager/RoomDetail/RoomDetailView.swift
> +    }
위에서 말한 것처럼 students 배열을 외부에서 주입받도록 구현하는게 어떨까요? 어차피 나중에 의존성을 외부에서 주입받게 구현해야할 것 같고, 프리뷰를 볼 때도 1명일 때 어떻게 보이는지, 2명일 때 어떻게 보이는지, 3명일 때 어떻게 보이는지를 프리뷰하기 위해서 initializer 를 수정하는게 좋아보입니다!

2022-07-23 11:52 UTC, HoJongPARK commented on dorm/dorm/Presenter/RoomManager/RoomDetail/SeparatedRoomView.swift
> +
UI 의 상태는 SeperatedRoomView 가 스스로 결정하도록 private 으로 외부에 감추는게 어떨까요!?

2022-07-27 11:00 UTC, Minkyeong-Ko commented on dorm/dorm/Presenter/RoomManager/RoomDetail/RoomDetailView.swift
> +    ]
수정했습니다!

2022-07-27 11:00 UTC, Minkyeong-Ko commented on dorm/dorm/Presenter/RoomManager/RoomDetail/RoomDetailView.swift
> +    }
수정했습니다!

2022-07-27 11:02 UTC, Minkyeong-Ko commented on dorm/dorm/Presenter/RoomManager/RoomDetail/SeparatedRoomView.swift
> +
이 부분은 제가 완벽히 이해는 못해서 확인해주시면 감사하겠습니다!

2022-07-27 14:34 UTC, Minkyeong-Ko commented
@HoJongPARK 제안해 주신 수정사항 반영하고 디자인, ScrollView -> TextView 수정까지 완료했습니다! 그리고 다음부터는 conflict 해결할 때 정신 똑바로 차리겠습니다,,

2022-07-28 00:33 UTC, HoJongPARK approved these changes
고생하셨습니다~~

2022-07-28 00:33 UTC, HoJongPARK commented on dorm/dorm/Presenter/RoomManager/RoomDetail/SeparatedRoomView.swift
> +        textView.font = UIFont.systemFont(ofSize: 90, weight: .semibold)
텍스트뷰의 사이즈가 90인 이유가 있나요??

2022-07-28 00:33 UTC, HoJongPARK commented on dorm/dorm/Presenter/RoomManager/RoomDetail/SeparatedRoomView.swift
> +    private var student: Student
아마 나중에 편집 기능이 추가된다면, student 데이터가 바뀔 수도 있기 때문에 var 로 설정하신 것인가요? 그러면 student 를 바꿀 수 있게 public 을 선언하거나, student 정보를 받아서 관련 UI Component 를 설정해주는 함수를 작성하는게 어떨까요?

```swift
func configure(_ student: Student) {
// 학생 정보를 받아서 관련 UI component 를 설정한다.
}
```

혹은 

```swift
var student: Student? {
    didSet {
        // student 관련 UIComponent 설정
    }
}
```

2022-07-28 00:55 UTC, Minkyeong-Ko commented on dorm/dorm/Presenter/RoomManager/RoomDetail/SeparatedRoomView.swift
> +        textView.font = UIFont.systemFont(ofSize: 90, weight: .semibold)
앗 제가 놓친 부분인데 어제 스크롤을 테스트하려고 폰트 크기를 최대로 올렸었습니다!

2022-07-28 01:52 UTC, unnnyong commented on dorm/dorm/Presenter/RoomManager/RoomDetail/SeparatedRoomView.swift
> +        if roomType != 1 {
```suggestion
        guard roomType == 1 else { return }
```

guard 문을쓴다면 아래의 인덴트도 사라지고, 빠르게 리턴할 수 있지 않을까합니다 ~

2022-07-28 03:17 UTC, Minkyeong-Ko commented on dorm/dorm/Presenter/RoomManager/RoomDetail/SeparatedRoomView.swift
> +        if roomType != 1 {
코드도 더 깔끔해지겠네요..!! 바로 적용해 보도록 하겠습니다 감사합니다!

2022-07-29 00:23 UTC, merged