Feat: Add RoomCoellectionViewCell & function that connect RoomCollectionViewCell with RoomCollectionView
DeveloperAcademy-POSTECH/MC3-Team-18-Momin pull request #23
Opened 2022-07-27 02:10 UTC by italsehf

## Changes

- Changed files
    - MockDatas.swift - 수정
    - RoomCollectionViewCell.swift - 추가
    - RoomCollectionViewController.swift - 수정

## New features

<img width="800" alt="image" src="https://user-images.githubusercontent.com/103008077/180637912-e6f2df8f-5e24-4940-a598-e326bbf19624.png">

- RoomCollectionViewCell 생성
- MockDatas를 활용하여 RoomCollectionViewCell의 label에 해당하는 정보 가져오기
- RoomCollectionView에 RoomCollectionViewCell 연결

## Review points

- RoomCollectionViewCell 생성 및 MockDatas의 데이터를 Cell에 연결
- RoomCollectionViewController에서 RoomCollectionView에 RoomCollectionViewCell을 연결

## Previous PR Comment

<img width="800" alt="스크린샷 2022-07-27 오전 10 03 36" src="https://user-images.githubusercontent.com/103008077/181144699-af492b60-f778-4aac-854c-a6a1ed756ab3.png">
- 가로에는 셀이 6개 / 세로에는 셀이 3개가 위치할 수 있도록 동적으로 비율을 계산하였습니다!

<img width="800" alt="스크린샷 2022-07-27 오전 10 03 30" src="https://user-images.githubusercontent.com/103008077/181144906-73b58b1b-6109-496b-8ca8-cc83a3a84b86.png">
- RoomCollectionViewCell 하나의 영역 안에 roundRectange이 해당 위치에 나타날 수 있도록 동적으로 비율을 계산하였습니다.

<img width="800" alt="스크린샷 2022-07-27 오전 10 03 22" src="https://user-images.githubusercontent.com/103008077/181145074-ee40c2de-3fa4-438d-877e-c41458c0ac41.png">
- view life cycle에 대해서 아직 명확하게 이해를 하지 못해서 view life cycle 안에 넣는게 맞다면 수정하도록 하겠습니다.

<img width="817" alt="스크린샷 2022-07-27 오전 10 03 14" src="https://user-images.githubusercontent.com/103008077/181145226-9eb24269-4dfd-42ba-97a8-7becc50e02ee.png">
- 반영하였습니다 :)

## Checklist

- [x] Is the branch you are merging on correct?
- [x] Do you comply with coding conventions?
- [x] Are there any changes not related to PR?
- [x] Has my code been self-reviewed?

2022-07-28 00:42 UTC, HoJongPARK requested changes
코멘트 단 내용들을 고려부탁드립니다!

2022-07-28 00:42 UTC, HoJongPARK commented on dorm/dorm/Presenter/RoomCollectionView/RoomCollectionViewCell.swift
> +    static let identifier = "RoomCollectionViewCell"
어제 지나가는 행인이 제시해준 방법으로 NSObject extension 을 생성했습니다! develop 를 pull 받은 후 따라해주세요

2022-07-28 00:42 UTC, HoJongPARK commented on dorm/dorm/Presenter/RoomManager/RoomManagerViewController.swift
> +    private var roomCollectionView: UICollectionView = {
RoomManagerView 에 이미 Collection View 를 설정해놨는데 그것을 사용해주세요.

2022-07-28 00:42 UTC, HoJongPARK commented on dorm/dorm/Presenter/RoomManager/RoomManagerViewController.swift
> +    private var roomCollectionView: UICollectionView = {
또한 코드로 View 를 짜면 ViewController 가 너무 커지기 때문에 UI 를 RoomManagerView 에서 관리하는데, 이것을 참고해주셔서 코드 재작성바랍니다.

2022-07-28 00:42 UTC, HoJongPARK commented on dorm/dorm/Presenter/RoomManager/RoomManagerViewController.swift
> +        collectionView.register(RoomCollectionViewCell.self, forCellWithReuseIdentifier: "RoomCollectionViewCell")
이 부분도 어제 지나가는 행인이 제시해준대로 Class 의 Name 을 직접ㅂ적으로 활용 부탁드립니다.

2022-07-28 00:48 UTC, italsehf commented on dorm/dorm/Presenter/RoomCollectionView/RoomCollectionViewCell.swift
> +    static let identifier = "RoomCollectionViewCell"
넵 참고해서 수정하겠습니다 ~

2022-07-28 00:49 UTC, italsehf commented on dorm/dorm/Presenter/RoomManager/RoomManagerViewController.swift
> +        collectionView.register(RoomCollectionViewCell.self, forCellWithReuseIdentifier: "RoomCollectionViewCell")
지나가는 행인을 따라가겠습니다 !

2022-07-29 02:33 UTC, italsehf commented on dorm/dorm/Presenter/RoomManager/RoomManagerViewController.swift
> +    private var roomCollectionView: UICollectionView = {
수정 완료⭐️

2022-07-29 02:36 UTC, unnnyong commented on dorm/dorm/Presenter/RoomManager/RoomCollectionViewCell.swift
> +    private let roundedRectangleUIView: UIView = {
```suggestion
    private let roundedRectangleView: UIView = {
```

보통은 UI는 뗍니다요 !

2022-07-29 02:37 UTC, unnnyong commented on dorm/dorm/Presenter/RoomManager/RoomManagerViewController.swift
> +        return CGSize(width: UIScreen.main.bounds.width / 6.98, height: UIScreen.main.bounds.height / 6.27)
6.98 과 6.27 의 의미는 무엇일까요 ?
이해하기 쉽도록 정수로 정의되면 좋을 것 같아요 ~

2022-07-29 07:03 UTC, italsehf commented on dorm/dorm/Presenter/RoomManager/RoomManagerViewController.swift
> +        return CGSize(width: UIScreen.main.bounds.width / 6.98, height: UIScreen.main.bounds.height / 6.27)
Cell이 화면에 가로로 6개, 세로로 3개씩 Hifi에서 배치하고자 했던 정확한 위치에 배치하려고 하다보니 정수로 표현되지 못했습니다ㅠ

2022-07-29 07:03 UTC, italsehf commented on dorm/dorm/Presenter/RoomManager/RoomCollectionViewCell.swift
> +    private let roundedRectangleUIView: UIView = {
바로 UI 떼버리겠습니다!

2022-07-29 07:58 UTC, HoJongPARK approved these changes

2022-07-29 08:44 UTC, merged