Feat/momin 47
DeveloperAcademy-POSTECH/MC3-Team-18-Momin pull request #26
Opened 2022-07-28 16:43 UTC by TaekH

## Changes

- Changed files
    - Add NotesView.swift
    - Add NotesViewController.swift

## New features
<img width="500" alt="image" src="https://user-images.githubusercontent.com/103012087/181592281-d8f595cb-f9e4-42c6-a6ed-5175dbc5e16a.gif">

- TextView 추가

## Review points

- write here

## Questions

- write here

## References

- write here 

## Checklist

- [ ] Is the branch you are merging on correct?
- [ ] Do you comply with coding conventions?
- [ ] Are there any changes not related to PR?
- [ ] Has my code been self-reviewed?

2022-07-29 00:43 UTC, HoJongPARK requested changes

2022-07-29 00:43 UTC, HoJongPARK commented on dorm/dorm/Presenter/Notes/NotesViewController.swift
> +        view = notesView
view 를 바꾸는건 loadView 를 override 해서 넣어줘야 해요.

RoomManagerViewController 나 다른 뷰컨을 참고해주세요

2022-07-29 01:01 UTC, TaekH commented on dorm/dorm/Presenter/Notes/NotesViewController.swift
> +        view = notesView
8f775b8b11b896d0695ab6ce0cdb11377006e90c 에서 수정완료입니다!

2022-07-29 02:35 UTC, unnnyong commented on dorm/dorm/Presenter/Notes/NotesView.swift
> +    lazy var notesField: UITextView = UITextView(frame: .zero)
```suggestion
    private lazy var notesField: UITextView = UITextView(frame: .zero)
```

2022-07-30 02:22 UTC, HoJongPARK approved these changes
수고하셨습니다~

2022-08-04 02:39 UTC, Minkyeong-Ko approved these changes
수고하셨습니다!

2022-08-04 03:06 UTC, merged