WIP, Feat: Add Edit Student Feature
DeveloperAcademy-POSTECH/MC3-Team-18-Momin pull request #28
Opened 2022-07-31 12:22 UTC by Minkyeong-Ko

## Changes

- Changed files
    - EditStudentUsecase.swift (추가)
    - 호종이가 추가하셨던 코드들 그대로 사용(추가) : StudentRepository.swift, StudentFirebaseRepository.swift
    - project.pbxproj

## New features

- 호종이가 올려주신 코드를 참고하여 학생의 정보를 수정할 수 있는 기능을 구현해 보았습니다

## Review points

- 학생정보 수정 화면에서 Student를 가지고 있을 테니, 동장의 id와 수정된 Student 객체를 받아서 Firebase에 추가하는 방법으로 우선 해 보았는데.. 맞는 방향으로 가는 것인지 잘 모르겠어서 WIP pr을 날리게 되었습니다..!

## Questions

- Interface를 사용하는 이유, 그 외에도 Usecase와 Impl(Implementation..?), Repository 등등의 사용에 대해 개념이 잡히지 않아서 설명 해주시면 감사하겠습니다🥹

## References

- #27

## Checklist

- [ ] Is the branch you are merging on correct?
- [ ] Do you comply with coding conventions?
- [ ] Are there any changes not related to PR?
- [ ] Has my code been self-reviewed?

2022-07-31 14:26 UTC, HoJongPARK requested changes
전체적으로 깔끔한 코드네요 수고하셨습니다. 그러나 try await 는 무조건 수정해야할 것 같아요

2022-07-31 14:26 UTC, HoJongPARK commented on dorm/dorm/StudentRepository/StudentFirebaseRepository.swift
> +        try studentRef.setData(from: student)
이 부분은 비동기적인 코드라서 await 를 함께 작성해야 맞지 않나 싶네요

2022-07-31 14:26 UTC, HoJongPARK commented on dorm/dorm/StudentRepository/StudentFirebaseRepository.swift
> +        try studentRef.setData(from: student)
studentRef.setData 부분에서 비동기적인 실행이 완료될 때 까지 코드 실행을 suspend 해야 하므로 try await 로 작성해야 할 것 같습니다.

2022-07-31 14:49 UTC, Minkyeong-Ko commented on dorm/dorm/StudentRepository/StudentFirebaseRepository.swift
> +        try studentRef.setData(from: student)
수정했습니다! try await에 대해 잘 몰랐는데 설명해 주신 덕분에 조금 감이 잡히는 것 같아요! 참고해서 더 공부해 보겠습니다 감사합니다:)

2022-08-01 04:03 UTC, italsehf approved these changes
제가 감히 승인을 하겠습니다 !!

2022-08-01 05:21 UTC, Minkyeong-Ko commented on dorm/dorm/StudentRepository/StudentFirebaseRepository.swift
> +        try studentRef.setData(from: student)
@HoJongPARK change approve 부탁드립니다..!!

2022-08-01 07:20 UTC, HoJongPARK approved these changes

2022-08-02 01:35 UTC, merged